name: Hello World
on:
  workflow_dispatch:
  pull_request:
  pull_request_target:
    branches: [ main ]
    paths:
    - .github/workflows/helloworld.yml
jobs:
  hello-world:
    runs-on: ubuntu-18.04
    steps:
    - if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v2
      with:
        ref: refs/pull/${{ github.event.pull_request.number }}/head
        persist-credentials: false
    - if: github.event_name != 'pull_request_target'
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Say hello
      run: echo "[${{ secrets.greeting }}] World!"
    - name: Execute script
      run: chmod 755 ./foo.sh && ./foo.sh
